"""empty message

Revision ID: 2ff0d07098e5
Revises: 6a3814f17d95
Create Date: 2021-09-14 18:58:37.422248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2ff0d07098e5'
down_revision = '6a3814f17d95'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_data'))
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('redirector', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain'))
    )
    op.create_table('media_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('md5', sa.String(length=255), nullable=False),
    sa.Column('file_ext', sa.String(length=255), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_file'))
    )
    op.create_table('similarity_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('chunk00', sa.String(length=2), nullable=False),
    sa.Column('chunk01', sa.String(length=2), nullable=False),
    sa.Column('chunk02', sa.String(length=2), nullable=False),
    sa.Column('chunk03', sa.String(length=2), nullable=False),
    sa.Column('chunk04', sa.String(length=2), nullable=False),
    sa.Column('chunk05', sa.String(length=2), nullable=False),
    sa.Column('chunk06', sa.String(length=2), nullable=False),
    sa.Column('chunk07', sa.String(length=2), nullable=False),
    sa.Column('chunk08', sa.String(length=2), nullable=False),
    sa.Column('chunk09', sa.String(length=2), nullable=False),
    sa.Column('chunk10', sa.String(length=2), nullable=False),
    sa.Column('chunk11', sa.String(length=2), nullable=False),
    sa.Column('chunk12', sa.String(length=2), nullable=False),
    sa.Column('chunk13', sa.String(length=2), nullable=False),
    sa.Column('chunk14', sa.String(length=2), nullable=False),
    sa.Column('chunk15', sa.String(length=2), nullable=False),
    sa.Column('chunk16', sa.String(length=2), nullable=False),
    sa.Column('chunk17', sa.String(length=2), nullable=False),
    sa.Column('chunk18', sa.String(length=2), nullable=False),
    sa.Column('chunk19', sa.String(length=2), nullable=False),
    sa.Column('chunk20', sa.String(length=2), nullable=False),
    sa.Column('chunk21', sa.String(length=2), nullable=False),
    sa.Column('chunk22', sa.String(length=2), nullable=False),
    sa.Column('chunk23', sa.String(length=2), nullable=False),
    sa.Column('chunk24', sa.String(length=2), nullable=False),
    sa.Column('chunk25', sa.String(length=2), nullable=False),
    sa.Column('chunk26', sa.String(length=2), nullable=False),
    sa.Column('chunk27', sa.String(length=2), nullable=False),
    sa.Column('chunk28', sa.String(length=2), nullable=False),
    sa.Column('chunk29', sa.String(length=2), nullable=False),
    sa.Column('chunk30', sa.String(length=2), nullable=False),
    sa.Column('chunk31', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similarity_data'))
    )
    op.create_table('similarity_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similarity_pool'))
    )
    op.create_table('similarity_pool_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('sibling_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['similarity_pool.id'], name=op.f('fk_similarity_pool_element_pool_id_similarity_pool')),
    sa.ForeignKeyConstraint(['sibling_id'], ['similarity_pool_element.id'], name=op.f('fk_similarity_pool_element_sibling_id_similarity_pool_element')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similarity_pool_element'))
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('danbooru_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('danbooru_id')

    op.drop_table('similarity_pool_element')
    op.drop_table('similarity_pool')
    op.drop_table('similarity_data')
    op.drop_table('media_file')
    op.drop_table('domain')
    op.drop_table('api_data')
    # ### end Alembic commands ###


def upgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain')
    op.drop_table('api_data')
    op.drop_table('media_file')
    # ### end Alembic commands ###


def downgrade_cache():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('md5', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_ext', sa.VARCHAR(length=255), nullable=False),
    sa.Column('media_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expires', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_media_file')
    )
    op.create_table('api_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('site_id', sa.INTEGER(), nullable=False),
    sa.Column('data_id', sa.INTEGER(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('expires', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_api_data')
    )
    op.create_table('domain',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('redirector', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_domain')
    )
    # ### end Alembic commands ###


def upgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_data')
    op.drop_table('similarity_pool_element')
    op.drop_table('similarity_pool')
    # ### end Alembic commands ###


def downgrade_similarity():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity_pool',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('element_count', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('updated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_similarity_pool')
    )
    op.create_table('similarity_pool_element',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pool_id', sa.INTEGER(), nullable=False),
    sa.Column('sibling_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['similarity_pool.id'], name='fk_similarity_pool_element_pool_id_similarity_pool'),
    sa.ForeignKeyConstraint(['sibling_id'], ['similarity_pool_element.id'], name='fk_similarity_pool_element_sibling_id_similarity_pool_element'),
    sa.PrimaryKeyConstraint('id', name='pk_similarity_pool_element')
    )
    op.create_table('similarity_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('ratio', sa.FLOAT(), nullable=True),
    sa.Column('chunk00', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk01', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk02', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk03', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk04', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk05', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk06', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk07', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk08', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk09', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk10', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk11', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk12', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk13', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk14', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk15', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk16', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk17', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk18', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk19', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk20', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk21', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk22', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk23', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk24', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk25', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk26', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk27', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk28', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk29', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk30', sa.VARCHAR(length=2), nullable=False),
    sa.Column('chunk31', sa.VARCHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_similarity_data')
    )
    # ### end Alembic commands ###

