"""Add upload image URLS

Revision ID: 5e85b082ac90
Revises: 
Create Date: 2021-04-22 07:33:13.759518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e85b082ac90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_urls',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('upload_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['upload_url_id'], ['upload_url.id'], ),
    sa.PrimaryKeyConstraint('upload_id', 'upload_url_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_urls')
    op.drop_table('upload_url')
    # ### end Alembic commands ###
