# APP\HELPERS\SIMILARITY_CONTROLLER.PY

# ## LOCAL IMPORTS
from ..storage import CACHE_DATA_DIRECTORY, CACHE_NETWORK_URLPATH


# ## FUNCTIONS

def CacheUrl(md5):
    return CACHE_NETWORK_URLPATH + md5 + '.jpg'
